### POST create address
POST http://localhost:3000/api/v1/address/create-address
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3Njg4NTE4NDEsImV4cCI6MTc2ODkzODI0MX0.V8RbNdxIYbsRvObhnrngjEJwTG7qM16u8_rakR8LuMoGE7AZ7CvcaMNWW9lPVcV1h9ykCA_gKIFnTZfA4Ytegg

{
  "country": "Mexico",
  "state": "Tlaxcala",
  "city": "Tlaxcala",
  "street": "Zafiro Norte",
  "postal_code": "90114",
  "is_primary": false
}

### POST update address
POST http://localhost:3000/api/v1/address/update-address/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3Njg4NTE4NDEsImV4cCI6MTc2ODkzODI0MX0.V8RbNdxIYbsRvObhnrngjEJwTG7qM16u8_rakR8LuMoGE7AZ7CvcaMNWW9lPVcV1h9ykCA_gKIFnTZfA4Ytegg

{
  "country": "Mexico",
  "state": "Guanajuato",
  "city": "Guanajuato",
  "street": "Principal",
  "postal_code": "2321",
  "is_primary": false
}

### POST set primary address
POST http://localhost:3000/api/v1/address/set-primary-address/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3Njg4NTE4NDEsImV4cCI6MTc2ODkzODI0MX0.V8RbNdxIYbsRvObhnrngjEJwTG7qM16u8_rakR8LuMoGE7AZ7CvcaMNWW9lPVcV1h9ykCA_gKIFnTZfA4Ytegg

### DELETE address
DELETE http://localhost:3000/api/v1/address/delete-address/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3Njg4NTE4NDEsImV4cCI6MTc2ODkzODI0MX0.V8RbNdxIYbsRvObhnrngjEJwTG7qM16u8_rakR8LuMoGE7AZ7CvcaMNWW9lPVcV1h9ykCA_gKIFnTZfA4Ytegg

### GET customer get customer addresses
GET http://localhost:3000/api/v1/address/get-customer-addresses
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3Njg4NTE4NDEsImV4cCI6MTc2ODkzODI0MX0.V8RbNdxIYbsRvObhnrngjEJwTG7qM16u8_rakR8LuMoGE7AZ7CvcaMNWW9lPVcV1h9ykCA_gKIFnTZfA4Ytegg

### GET primary address
GET http://localhost:3000/api/v1/address/get-primary-address
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3Njg4NTE4NDEsImV4cCI6MTc2ODkzODI0MX0.V8RbNdxIYbsRvObhnrngjEJwTG7qM16u8_rakR8LuMoGE7AZ7CvcaMNWW9lPVcV1h9ykCA_gKIFnTZfA4Ytegg

### GET customers by location
GET http://localhost:3000/api/v1/address/get-customers-by-location/Mexico/Tlaxcala/Tlaxcala
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3Njg4NTE4NDEsImV4cCI6MTc2ODkzODI0MX0.V8RbNdxIYbsRvObhnrngjEJwTG7qM16u8_rakR8LuMoGE7AZ7CvcaMNWW9lPVcV1h9ykCA_gKIFnTZfA4Ytegg

### GET customers by postal code
GET http://localhost:3000/api/v1/address/get-customers-by-postal-code/90114
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3Njg4NTE4NDEsImV4cCI6MTc2ODkzODI0MX0.V8RbNdxIYbsRvObhnrngjEJwTG7qM16u8_rakR8LuMoGE7AZ7CvcaMNWW9lPVcV1h9ykCA_gKIFnTZfA4Ytegg

### GET location statistics
GET http://localhost:3000/api/v1/address/get-location-statistics
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3Njg4NTE4NDEsImV4cCI6MTc2ODkzODI0MX0.V8RbNdxIYbsRvObhnrngjEJwTG7qM16u8_rakR8LuMoGE7AZ7CvcaMNWW9lPVcV1h9ykCA_gKIFnTZfA4Ytegg
