@baseUrl = http://localhost:3000/api/v1/category
@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3NzUyNDY5MjIsImV4cCI6MTc3NzgzODkyMn0.FR5z1zWVVTuaUD2ffx2nNvTtboA7Qh5A8rCOwAxLPEzpp4Em0yGJq7uOtzP8dEap-9XzKqr2fYo6ZhdGa9_aOg

### POST create category
POST {{baseUrl}}/create
Authorization: {{token}}

{
  "name": "Refurbished Laptops",
  "parent_id": 11,
  "active": true
}

### PUT update category
PUT {{baseUrl}}/update/11
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Computers & Laptops Updated",
  "parent_id": 1,
  "active": true
}

### DELETE category by id
DELETE {{baseUrl}}/delete/1
Authorization: {{token}}

### GET category by id
GET {{baseUrl}}/1
Authorization: {{token}}

### GET category stats
GET {{baseUrl}}/stats
Authorization: {{token}}
