### GET customer by id
GET http://localhost:3000/api/v1/customer/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3Njg3NzIxMTAsImV4cCI6MTc2ODg1ODUxMH0.yRzfRz5ptWZOQSrE05YH3sMOezd21Q9ONLdICoC3nBJ68dLZoEfyx4wgA21ZUSuN0Ogn00FoTaVnTyWVIcQMyg

### GET customer registration trend
GET http://localhost:3000/api/v1/customer/registration-trend/YEAR
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3Njg0OTg1NjIsImV4cCI6MTc2ODU4NDk2Mn0.gbkD3HGsvQfPt93UyLrdKVp5r9MGxnSoeMQkoNBu4iQlfAEhk2M4jn3OSAfaKgQayuJYMOsti5iEExREY9Yu3g

### GET customer by gender
GET http://localhost:3000/api/v1/customer/gender/MALE
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3Njg0OTg1NjIsImV4cCI6MTc2ODU4NDk2Mn0.gbkD3HGsvQfPt93UyLrdKVp5r9MGxnSoeMQkoNBu4iQlfAEhk2M4jn3OSAfaKgQayuJYMOsti5iEExREY9Yu3g

### GET customer by segment demographics
GET http://localhost:3000/api/v1/customer/segment-demographics/MEX/MALE/10/40
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3Njg0OTg1NjIsImV4cCI6MTc2ODU4NDk2Mn0.gbkD3HGsvQfPt93UyLrdKVp5r9MGxnSoeMQkoNBu4iQlfAEhk2M4jn3OSAfaKgQayuJYMOsti5iEExREY9Yu3g

### GET customer inactive
GET http://localhost:3000/api/v1/customer/inactive
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3Njg0OTg1NjIsImV4cCI6MTc2ODU4NDk2Mn0.gbkD3HGsvQfPt93UyLrdKVp5r9MGxnSoeMQkoNBu4iQlfAEhk2M4jn3OSAfaKgQayuJYMOsti5iEExREY9Yu3g

### GET customer active rate
GET http://localhost:3000/api/v1/customer/active-rate
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3Njg0OTg1NjIsImV4cCI6MTc2ODU4NDk2Mn0.gbkD3HGsvQfPt93UyLrdKVp5r9MGxnSoeMQkoNBu4iQlfAEhk2M4jn3OSAfaKgQayuJYMOsti5iEExREY9Yu3g

### GET customer by age group
GET http://localhost:3000/api/v1/customer/age-group
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3Njg0OTg1NjIsImV4cCI6MTc2ODU4NDk2Mn0.gbkD3HGsvQfPt93UyLrdKVp5r9MGxnSoeMQkoNBu4iQlfAEhk2M4jn3OSAfaKgQayuJYMOsti5iEExREY9Yu3g

### GET customer country count
GET http://localhost:3000/api/v1/customer/country-count
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3Njg4NDMzNTEsImV4cCI6MTc2ODkyOTc1MX0.HxJmxEXWgla18C6sdWtZQUaQ-uBDbhk8MSPQPN31Duo7LWg9fqFT6HrSuL6aJIk-l_XWrU7UMPcZVBSf0mhq0Q

### GET customer registrations by country code
GET http://localhost:3000/api/v1/customer/registration-by-country-code
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3Njg0OTg1NjIsImV4cCI6MTc2ODU4NDk2Mn0.gbkD3HGsvQfPt93UyLrdKVp5r9MGxnSoeMQkoNBu4iQlfAEhk2M4jn3OSAfaKgQayuJYMOsti5iEExREY9Yu3g

### GET customers with password reset code
GET http://localhost:3000/api/v1/customer/customers-with-password-reset-code
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MywiZW1haWwiOiJhbmEuaGVybmFuZGV6QGVtYWlsLmNvbSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE3Njg0OTg1NjIsImV4cCI6MTc2ODU4NDk2Mn0.gbkD3HGsvQfPt93UyLrdKVp5r9MGxnSoeMQkoNBu4iQlfAEhk2M4jn3OSAfaKgQayuJYMOsti5iEExREY9Yu3g
