services:
  db:
    image: postgres:15.4
    container_name: auth-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: ecommerce
      POSTGRES_INITDB_ARGS: --encoding=UTF-8

  api:
    build: .
    container_name: auth-api
    ports:
      - "8080:8080"
    depends_on:
      - db
